language: rust

matrix:
  include:
    # Linux builds use the `rust-slave-dist` image so we link them against a
    # "super old glibc" to ensure that it runs on as many platforms as possible.
    - os: linux
      dist: xenial
      env: TARGET=x86_64-unknown-linux-gnu NO_ADD=1
      rust: nightly
      script:
        - cargo clippy --all --examples --tests
    - dist: xenial
      env: TARGET=x86_64-unknown-linux-gnu NO_ADD=1
      rust: stable
      script:
        - bash ci/run.sh

install:
  - if [ -z "$NO_ADD" ]; then rustup target add $TARGET; fi
  - rustup component add rustfmt clippy
