name: rustdoc
on:
  push:
    branches:
      - 'master'
      - '!gh-pages'
  pull_request:

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          rustup toolchain install nightly
          rustup default nightly
      - run: cargo doc --workspace --document-private-items
      - name: Commit docs to gh-pages branch
        working-directory: target/doc
        run: |
          # Bypassing Jekyll on GitHub Pages
          touch .nojekyll
          REV=$(git rev-parse --short HEAD)
          git init
          git config user.name "Actions"
          git config user.email ""
          git config --global core.autocrlf false
          git add -A .
          git commit -qm "Documentation for ${{github.repository}}@${REV}"
        shell: bash
      - name: Push gh-pages to GitHub
        working-directory: target/doc
        run: |
          git remote add upstream https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push -q upstream HEAD:gh-pages --force
